### PR TITLE
Feature/tilted path gait

### PR DESCRIPTION
**Pull request by marnixbrands**
## Description
 Added new gait files for the first steps onto the tilted path. There are three different versions; one uses a side step to get onto the tilted path, one stepping straight onto the tilted path starting with the right foot and one straight starting with the left foot.

## Changes
 Added tilted path gait files to test_versions-v folder

### CODE REVIEW

**Review by gaiavdh — APPROVED** [review]

**Review by Olavhaasie — CHANGES_REQUESTED** [review]
Are you aware that the side first and second start gait do not end in a standing position?

**Comment by gaiavdh** [comment]
Yes, we are aware that the first starting step does not end in the standing position, this is deliberate as the surface is tilted (one leg is a little bent). In the state machine, we have made an additional idle state in between the first and second starting step of the Tilted Path. The second step, however, should end in standing position, but this is the case when I open it in the gait generator.

**Comment by gaiavdh** [comment]
Yes, we are aware that the first starting step does not end in the standing position, this is deliberate as the surface is tilted (one leg is a little bent). In the state machine, we have made an additional idle state in between the first and second starting step of the Tilted Path. The second step is indeed wrong; it should end in standing and this is also the case in the gait, but we made a mistake in the state machine. Will fix that!

**Comment by Olavhaasie** [comment]
See https://github.com/project-march/march/pull/430#discussion_r362516650 for fix

**Review by Olavhaasie — APPROVED** [review]

**Pull request merged**
