### PR TITLE
Change subgaits to new format

### PR DESCRIPTION
**Pull request by Olavhaasie**
Closes PM-516

## Description
This changes all subgait files to a new and better format. Instead of saving the setpoints in a `setpoints` and `trajectory` list they are now stored per joint. This method of saving is better compatible with the way we use it in the gait selection and gait generator and it is shorter for a lot of gaits. I automatically transformed all subgaits using this Python script:
```python
#!/usr/bin/env python3
import os
import sys

import yaml


def create_joints(setpoints, trajectory):
    joint_names = trajectory['joint_names']
    joints = dict([(name, []) for name in joint_names])
    if len(setpoints) == 0:
        for p in trajectory['points']:
            for i, name in enumerate(joint_names):
                joints[name].append({
                    'position': p['positions'][i],
                    'velocity': p['velocities'][i],
                    'time_from_start': p['time_from_start']
                })
        return joints
    if len(setpoints) != len(trajectory['points']):
        print('Setpoints and trajectory points are not of same length')
        return 'stoel'
    for s, p in zip(setpoints, trajectory['points']):
        for name in s['joint_names']:
            i = joint_names.index(name)
            joints[name].append({
                'position': p['positions'][i],
                'velocity': p['velocities'][i],
                'time_from_start': p['time_from_start']
            })
    return joints


for line in sys.stdin:
    file_path = line.strip()
    print('processing {f}'.format(f=file_path))
    with open(file_path, 'r+') as f:
        subgait = yaml.load(f, Loader=yaml.SafeLoader)
        new_format = {
            'description': subgait['description'],
            'duration': subgait['duration'],
            'gait_type': subgait['gait_type'] if 'gait_type' in subgait else '',
            'joints': create_joints(subgait.get('setpoints', []), subgait['trajectory']),
            'name': os.path.basename(os.path.dirname(file_path)),
            'version': os.path.splitext(os.path.basename(file_path))[0],
        }

        f.seek(0, os.SEEK_SET)
        f.write(yaml.dump(new_format))
        f.truncate()
```

## Changes
* Transformed all subgaits to the new format

### CODE REVIEW

**Review by Roelemans — COMMENTED** [review]
I see you ordered the elements of the gait file alfabetically. Wouldn't it be better to put "name" on top and "joints" at the bottom? This way it would become a bit more human readable; at least you would be able to quickly discern what gait it is.

**Comment by Roelemans** [comment]
When I import and export a subgait, the format changes:
image

**Comment by Olavhaasie** [comment]
> I see you ordered the elements of the gait file alfabetically. Wouldn't it be better to put "name" on top and "joints" at the bottom? This way it would become a bit more human readable; at least you would be able to quickly discern what gait it is.

I tried this but PyYaml orders the dictionary alphabetically and if I wanted to do this I would have to use a Ordered Dictionary, which I think wasn't worth it, but now you mention it I will look into it.

> When I import and export a subgait, the format changes:

I feared that this would happen. In the script I was exporting the same objects so PyYaml created identifiers, but when importing they all become their own objects. I will make them all objects instead of references.

**Comment by Olavhaasie** [comment]
> > I see you ordered the elements of the gait file alfabetically. Wouldn't it be better to put "name" on top and "joints" at the bottom? This way it would become a bit more human readable; at least you would be able to quickly discern what gait it is.
> 
> I tried this but PyYaml orders the dictionary alphabetically and if I wanted to do this I would have to use a Ordered Dictionary, which I think wasn't worth it, but now you mention it I will look into it.
> 

I will not do this in this PR, since that would require subclassing `OrderedDict` and using yaml in another way (https://stackoverflow.com/questions/16782112/can-pyyaml-dump-dict-items-in-non-alphabetical-order), which I think is not worth it

**Review by Roelemans — APPROVED** [review]

**Review by Joris-JW — APPROVED** [review]

**Pull request merged**
